enabled: true
commit_template: |
  Restyled by ${restyler.name}
pull_requests: true
statuses:
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
  error: true           # Red if we encounter errors restyling